language: java
before_install:
  - "export DISPLAY=:99.0"
  - "export TERM=dumb"
  - "sh -e /etc/init.d/xvfb start"

script:
    - TERM=dumb ./gradlew  jar  javadoc test --stacktrace
cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk11

# for running tests on Travis CI container infrastructure for faster builds
sudo: true
dist: trusty


after_failure:
  - "cat ./build/test-results/*.xml"
